source 'https://rubygems.org'

gem 'coffee-rails'
gem 'compass'
gem 'compass-rails'
gem 'execjs'
gem 'haml'
gem 'jquery-rails'
gem 'maruku'
gem 'pandoc-ruby'
gem 'rails', '~> 4.1.0'
gem 'sass-rails', '~> 4.0'
gem 'sqlite3'
gem 'thin'
gem 'uglifier', '>= 1.0.3'
